### ISSUE TITLE
Bug: Quote and author come up as undefined

### ISSUE THREAD

**Issue by ckim77** [seths10/Quotes-Generator#181] opened 2023-03-10 21:19 UTC
I've clicked on the generate quote button about a total of 100 times, and an undefined entry for the quote and author came up twice.
Screenshot: https://user-images.githubusercontent.com/90224498/224430324-90ec71c8-6751-4703-b1a0-a9a739e3594e.png

**Comment by niikkhilsharma** [comment] 2023-03-27 00:19
Yes! Man You're right I do tried in and found the same.
I would like to solve this as I have exactly faced the same thing. So, I can solve it better. Please assign it to me @ckim77 

<img width="1454" alt="Screenshot 2023-03-27 at 5 48 53 AM" src="https://user-images.githubusercontent.com/95525120/227814156-f586207d-0ffc-4c13-abad-e5ade483939b.png">

**Please assign it to me @ckim77 @seths10 I know what the issue is and how to solve it.**
Thank You!

**Closed as completed** 2023-10-24 18:26 UTC
Labels: good first issue, hacktoberfest, hacktoberfest-accepted
